### ISSUE TITLE
HEX for ESP32 upload

### ISSUE THREAD

**Issue by Dfinitski** [pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino#4]
Hi. I am not able to compile this project. Where can I find ready to upload HEX file ?
It would be perfect keep releases here.

**Comment by pe0mgb** [comment]
David,Sorry, I have no idea how to make a hex file for the ESP32. I will try to figure it  out.Also to upload I have to check.Regards Gert PE0MGBVerzonden vanaf Samsung-tablet.
-------- Oorspronkelijk bericht --------Van: David Fainitski <notifications@github.com> Datum: 17-11-20  22:41  (GMT+01:00) Aan: pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino <SI4735-Radio-ESP32-Touchscreen-Arduino@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Onderwerp: [pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino] HEX for ESP32 upload (#4) 
Hi. I am not able to compile this project. Where can I find ready to upload HEX file ?
It would be perfect keep releases here.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino/issues/4",
"url": "https://github.com/pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino/issues/4",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Dfinitski** [comment]
Hi. Try Sketch -> Export compiled binary

**Comment by leogoto** [comment]
Hi David,

Here is hex file.

Leo/WH2Q


On Tue, 17 Nov 2020 15:36:12 -0800
David Fainitski <notifications@github.com> wrote:

> Hi. Try Sketch -> Export compiled binary
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino/issues/4#issuecomment-729278296

-- 
Leo Gotoh <LeoGoto@yahoo.co.jp>
http://travelx.org

**Comment by Dfinitski** [comment]
Hi, Leo.
Where is exactly ? Please give a link.

**Comment by leogoto** [comment]
Hi David,

I do compiling.


On Tue, 17 Nov 2020 19:12:07 -0800
David Fainitski <notifications@github.com> wrote:

> Hi, Leo.
> Where is exactly ? Please give a link.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/pe0mgb/SI4735-Radio-ESP32-Touchscreen-Arduino/issues/4#issuecomment-729348609

-- 
Leo Gotoh <LeoGoto@yahoo.co.jp>
http://travelx.org

**Comment by Dfinitski** [comment]
Yes, "Export compiled binary" option creates bin file in the same directory where placed ino file.
Later everyone could upload that file into ESP32 without compilation of the project.
Sorry, initially I thought hex files format is working binary file for Arduino.
No, bin file of course.
